[project]
name = "nye"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.7.10"
dependencies = [
    "flask>=2.2.5",
    "flask-socketio>=5.5.0",
    "requests>=2.31.0",
]
